{% set name = "eemont" %}
{% set version = "2025.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eemont-{{ version }}.tar.gz
  sha256: 9c6e2ea4338bc5932b44b2d97de399f4b904a6e8d0f0c7b4a1110d407eaaeb46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=3.8
    - beautifulsoup4
    - ee_extra >=2025.7.2
    - numpy
    - pandas
    - python-box >=6.0.0
    - geopy
    - requests

test:
  imports:
    - eemont
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davemlz/eemont
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package that extends Google Earth Engine
  doc_url: https://eemont.readthedocs.io/
  dev_url: https://github.com/davemlz/eemont

extra:
  recipe-maintainers:
    - davemlz
